language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.4

before_install: echo 'xdebug.mode = "coverage"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - vendor/bin/phpunit --verbose

matrix:
  fast_finish: true
  include:
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
